# Generated by Django 4.2.7 on 2023-12-03 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la cabaña')),
                ('descripcion', models.TextField(verbose_name='Descripción de la cabaña')),
                ('num_habitaciones', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Número de habitaciones')),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Capacidad de la cabaña')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio por noche')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Está disponible?')),
                ('foto', models.ImageField(blank=True, upload_to='fotos_cabanas/', verbose_name='Foto de la cabaña')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
            ],
        ),
    ]
